---
title: "Initial Data Preprocessing"
author: "JC"
format: html
editor: visual
---

# Reading Data and Loading Libraries

```{r}
library(tidyverse)
```

```{r}
path <- "D:/Portfolio Projects/rotten_tomatoes_empirical_bayes/Data/Raw/rotten_tomatoes_movies.csv"
df <- as.data.frame(read_csv(path, show_col_types = FALSE))
head(df)
```

# Selecting Variables of Interest

```{r}
movie_df <- df |> 
  select(rotten_tomatoes_link, movie_title, original_release_date,
         tomatometer_rating, tomatometer_count, audience_rating, audience_count)
head(movie_df)
```

# Dealing with missing values

```{r}
movie_df <- movie_df |> 
  filter(!if_any(c(audience_rating,audience_count,tomatometer_rating,
                   tomatometer_count), is.na))
```

# Constructing Fresh Critics Count and Fresh Audience Count

```{r}
movie_df <- movie_df |> 
  mutate(tomato_meter_fresh_critics_count = round((1/100)*tomatometer_rating*
            tomatometer_count),
         audience_rating_fresh_count = round((1/100) * audience_rating *
                                               audience_count))
head(movie_df)
```

# Saving Data

```{r}
save(movie_df, file = "D:/Portfolio Projects/rotten_tomatoes_empirical_bayes/Data/Processed/movie_df.RData")
```
